[tox]
envlist = py312, lint, format
isolated_build = True

[testenv]
deps =
    torch>=2.7.0
    torchvision>=0.22.0
    lightning>=2.2.1
    numpy>=1.26.4
    h5py>=3.10.0
    pyyaml>=6.0.1
    tqdm>=4.66.2
    matplotlib>=3.8.3
    seaborn>=0.13.2
    pandas>=2.2.1
    pytest>=8.0.2
index_url =
    https://download.pytorch.org/whl/cu128
setenv =
    CUDA_VISIBLE_DEVICES=
    FORCE_CPU=1
commands =
    pytest tests

[testenv:lint]
deps =
    ruff>=0.3.0
commands =
    ruff check .

[testenv:format]
deps =
    ruff>=0.3.0
commands =
    ruff format --check .

[pytest]
addopts = -v -ra -q
testpaths = tests
pythonpath = src
